version: '3.8'

services:
  proxy:
    container_name: proxy
    image: caddy:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    expose:
      - 8000
    command: /start.sh
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env/.dev
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=commissioner
    volumes:
      - pgdb:/var/lib/postgresql/data

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile
    ports:
      - 8081:80

  redis:
    container_name: redis
    image: redis
  
  # tacacs:
  #   container_name: tacacs
  #   image: lfkeitel/tacacs_plus:alpine
  #   volumes:
  #     - ./tacacs/tac_plus.cfg:/etc/tac_plus/tac_plus.cfg
  #   expose:
  #     - 49

volumes:
  pgdb: